---
title: "rapportProjet"
author: "Mariette"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(gsheet)
library(dplyr)
```

## Importer le google sheet


```{r}
library(gsheet)

agroListe <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1CzQZoqGDfIPUUQDyYNcvDH2TmrvEc9c4xngdPa4O80M/edit?usp=sharing")
```

# Supprimerla colonne Horodateur

```{r}
library(dplyr)
agroListe$Horodateur <- NULL
```

## Renommer les noms des colonnes

```{r}
library(dplyr)

agroListe <- agroListe%>%
  dplyr::rename(nom =`Nom de l'apprenant`)

```

```{r}
colnames(agroListe)
```

```{r}
library(dplyr)

agroListe <- agroListe%>%
  dplyr::rename(prenom =`Prénoms de l'apprenant`)

```

```{r}
colnames(agroListe)
```


```{r}
agroListe <- agroListe%>%
  dplyr::rename(contact =`Contact de l'apprenant`)
```

```{r}
colnames(agroListe)
```

```{r}
agroListe <- agroListe%>%
  dplyr::rename(email = `Email de l'apprenant`)
```


```{r}
agroListe <- agroListe%>%
  dplyr::rename(residence=`Lieu de résidence (commune/arrondissement)`)
```

```{r}
colnames(agroListe)
```

```{r}
agroListe <- agroListe%>%
  dplyr::rename(diplome = `Niveau d'étude (avant la formation)`)
```

```{r}
agroListe <- agroListe%>%
  dplyr::rename(domaine=`Domaines de formation 
`)
```

```{r}
colnames(agroListe)
```

```{r}
agroListe <- agroListe%>%
  dplyr::rename(periode=`Durée de la formation 
`)
```

```{r}
agroListe <- agroListe%>%
  dplyr::rename(centre=`Nom du centre de formation 
`)
```

```{r}
colnames(agroListe)
```

```{r}
agroListe <- agroListe%>%
  dplyr::rename(localisation=`Localisation du centre de formation (commune/arrondissement)
`)
```

```{r}
agroListe <- agroListe%>%
  dplyr::rename(an=`Année d'obtention du diplôme en entrepreneuriat agricole 
`)
```

```{r}
agroListe <- agroListe%>%
  dplyr::rename(occupation=`Occupation actuelle 
`)
```

```{r}
colnames(agroListe)
```



```{r}
library(dplyr)
agroListeAfter2020 <- filter(agroListe, an > 2020)
```


```{r}
library(dplyr)
agroListeAft <- filter(agroListe, )
```

#Faire des visuels
library(ggplot2)
library(ggthemes)

```{r}

```








